--
- name: update web servers
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: nano install
      apt: name=nano state=latest
    - name: nano install
      apt: name=vsftpd state=latest
    - name: Create group students
      group:
        name: students
        state: present
    - name: Adding user {{ user }}
      user:
        name: student
        shell: /bin/bash
        password: $6$saltstring$adDbXsJjcDlq2662QPgd.tkSOVmnG9Tt3oXl4HR60SusC3AGjirnDenVZp3DGwLwqy6iYKCzannhaX9DR7>
        groups: students
        append: yes
    - name: Creates directory
      file:
        path: /src/www
        state: directory
        owner: student
        group: students
        mode: 0775
        recurse: yes
